format = """\
[](bg:#1b1d1e fg:#A85E75)\
[ ](bg:#A85E75 fg:#FCF392)\
[](fg:#A85E75 bg:#503584)\
$time\
[](fg:#503584 bg:#605189)\
$directory\
[](fg:#605189 bg:#FCF392)\
$git_branch\
$git_status\
$git_metrics\
[](fg:#FCF392 bg:#1b1d1e)\
$kubernetes\
$character
"""

[directory]
format = "[ ﱮ $path ]($style)"
style = "fg:#E4E4E4 bg:#605189"

[git_branch]
format = '[ $symbol$branch(:$remote_branch) ]($style)'
symbol = "  "
style = "fg:#503584 bg:#FCF392"

[git_status]
format = '[$all_status]($style)'
style = "fg:#503584 bg:#FCF392"

[git_metrics]
format = "([+$added]($added_style))[]($added_style)"
added_style = "fg:#503584 bg:#FCF392"
deleted_style = "fg:bright-red bg:235"
disabled = false

[hg_branch]
format = "[ $symbol$branch ]($style)"
symbol = " "

[cmd_duration]
format = "[  $duration ]($style)"
style = "fg:bright-white bg:18"

[character]
success_symbol = ''
error_symbol = ''

[time]
disabled = false
time_format = "%R" # Hour:Minute Format
style = "bg:#1d2230"
format = '[[ 󱑍 $time ](bg:#503584 fg:#FFCEEA)]($style)'
[kubernetes]
symbol = '󰆧 '
format = " [$symbol$context( \\($namespace\\))]($style) "
style = "bright-blue"
disabled = false
